spring.jpa :
    hibernate.ddl-auto : update
    show-sql : true

spring.datasource :
  url : jdbc:mysql://localhost/school
  username : root
  password : MaiMai1@3
  driver-class-name : com.mysql.cj.jdbc.Driver

server:
  port: 8082